name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
      - name: Install Rust on ARM64
        if: ${{ runner.arch == 'ARM64' }}
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Build
        run: ${{ (matrix.os == 'windows-11-arm' && '~\.cargo\bin\') || '' }}cargo build --verbose --release
      - uses: actions/upload-artifact@v4
        with:
          name: discord-ls-${{ runner.os }}-${{ runner.arch }}
          path: |
            target/release/discord-ls
            target/release/discord-ls.exe
          if-no-files-found: error
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-24.04-arm
          - ubuntu-latest
          - windows-11-arm
          - windows-latest
